### PR TITLE
fix: call to undefined function get_plugin_data()

### PR DESCRIPTION
**Pull request by sy-records**
@MartinKolarik Hello, is this plugin still maintained?

### CODE REVIEW

**Comment by sy-records** [comment]
fix #32

**Comment by MartinKolarik** [comment]
We never actually got to fully finishing and publishing this. I see this PR changes a lot of unrelated code, is that needed because of WPCS?

**Comment by sy-records** [comment]
Yes, because of wpcs, CI cannot pass.
If you don't use wpcs, I will roll it back, what do you think?

**Comment by MartinKolarik** [comment]
Let's keep it, thanks for the PR.

**Pull request merged**
